const Map <String , String> ar ={
 'Log in' : 'تسجيل دخول',
 'Sign up' : 'انشاء حساب جديد',
 'Language' : 'اللغة',
  'Request' : 'الأشعارات',
  'Favorirs' : 'المفضلة',
  'Account' : 'الحساب',
 'LogOut' : 'تسجيل الخروج',
 'AboutUs' : 'معلومات عنا',
 'prudects' : 'المنتجات',
 'Username' : 'الأسم',
 'Name of prudect' : 'اسم المنتج',
 'Expiration date' : 'تاريخ انتهاء الصلاحية',
 'choose a Classification' : 'التصنيف',
 'Phone Number' : 'رقم الهاتف',
 'Quantity' : 'الكمية',
 'The price' : 'السعر',
 'Percentage 30 days before expiration' : 'النسبة المئوية قبل انتهاء الصلاحية ب مجهول يوم',
 'Percentage 15 days before expiration' : 'النسبة المئوية قبل انتهاء الصلاحية ب مجهول يوم',
 'Except that' : 'ماعدا ذلك',
 'ADD PHOTO' : 'اضافة صورة',
 'Send' : 'ارسال',
 'E-mail' : 'الأيميل',
 'Password' : 'كلمة السر',
 'Forgot Password' : 'هل نسيت كلمة السر؟',
 'Check' : 'تحقق',
 'confirm Password':'تأكيد كلمة المرور',
 'Edit' : 'تعديل',
 'Medicines' : 'ادوية',
 'Canned food' : 'طعام معلب',
 'Foods' : 'طعام',
 'tools' : 'أدوات',
};