const Map <String , String> en ={
 'Log in' : 'Log in',
 'Sign up' : 'Sign up',
 'Language' : 'Language',
 'Request' : 'Request',
 'Favorirs' : 'Favorirs',
 'Account' : 'Account',
 'LogOut' : 'LogOut',
 'AboutUs' : 'AboutUs',
 'prudects' : 'prudects',
 'Username' : 'User Name',
 'Name of prudect' : 'Name of prudect',
 'Expiration date' : 'Expiration Date',
 'choose a Classification' : 'Classification',
 'Phone Number' : 'Phone Number',
 'Quantity' : 'Quantity',
 'The price' : 'The price',
 'Percentage 30 days before expiration' : 'Percentage X days before expiration',
 'Percentage 15 days before expiration' : 'Percentage X days before expiration',
 'Except that' : 'Except that',
 'ADD PHOTO' : 'Add Photo',
 'Send' : 'Send',
 'E-mail' : 'E-mail',
 'Password' : 'Password',
 'Forgot Password' : 'Forgot Password?',
 'Check' : 'Check',
 'confirm Password':'confirm Passwprd',
 'Edit' : 'Edit',
 'Medicines' : 'Medicines',
 'Canned food' : 'Canned Food',
 'Foods' : 'Foods',
 'tools' : 'Tools',
};